-----
----- Generated by EmmyLua(https://github.com/EmmyLua)
----- Created by ethereal.
----- DateTime: 2025/9/4 14:41
-----
---- 优惠卷id
--local voucherId = ARGV[1]
---- 用户id
--local userId = ARGV[2]
----key列表
--local stockKey = 'seckill:stock:' .. voucherId
--local orderKey = 'seckill:order:' .. voucherId
---- 判断库存是否充足
--local stock = tonumber(redis.call('get', stockKey))
--if stock == nil or stock <= 0 then
--    -- 库存不足，返回1
--    return 1
--end
----判断用户是否下过单
--if(redis.call('sismember', orderKey, userId) == 1) then
--    -- 下过单，返回2
--    return 2
--end
----扣减库存
--redis.call('incrby', stockKey, -1)
---- 将用户加入set集合
--redis.call('sadd', orderKey, userId)
---- 可以购买
--return 0
--

local voucherId = ARGV[1]
local userId = tostring(ARGV[2])
local orderId = ARGV[3]

local stockKey = 'seckill:stock:' .. voucherId
local orderKey = 'seckill:order:' .. voucherId

-- 判断用户是否已下单
if redis.call('sismember', orderKey, userId) == 1 then
    return 2  -- 已下单
end

-- 获取库存
local stock = tonumber(redis.call('get', stockKey))
if not stock or stock <= 0 then
    return 1  -- 库存不足
end

-- 扣减库存并记录用户
redis.call('decr', stockKey)
redis.call('sadd', orderKey, userId)

--添加消息队列
redis.call('xadd', 'stream.orders', '*', 'userId', userId, 'voucherId', voucherId, 'id', orderId)
return 0
